### ISSUE TITLE
What every Gopher should know about Elixir

### ISSUE THREAD

**Issue by mishudark** [GolangBCN/talks#1]
---
type: standard
level: medium 
twitter: @mishudark
---

- [x] I have read and agreed the [Talk standards](https://github.com/GolangBCN/talks#talk-standards)

# What every Gopher should know about Elixir
We love Go, but is not the only amazing language out there, every gopher should know what Elixir can offer in terms of  reliability, real-time and fault tolerance

**Comment by gonzaloserrano** [comment]
❤️  BEAM & Elixir so 💯

**Comment by smoya** [comment]
Talk scheduled on 30th January, 2018.

cc @mishudark

**Comment by gonzaloserrano** [comment]
👍

**Comment by smoya** [comment]
Published: 
https://www.meetup.com/Golang-Barcelona/events/246607965

**Comment by smoya** [comment]
Finally, it was not scheduled due to @mishudark personal circumstances. It will be rescheduled for any other next meetup.
