### ISSUE TITLE
Dynamical extending and patching Go apps using plugins

### ISSUE THREAD

**Issue by buger** [GolangBCN/talks#10]
* type: standard
* level: medium
* language: english
* twitter: https://twitter.com/buger
* email (optional): [leonsbox@gmail.com](mailto:leonsbox@gmail.com)"

- [x] I have read and agreed the [Talk standards](https://github.com/GolangBCN/talks#talk-standards)

# Dynamical extending and patching Go apps using plugins

At Tyk.io we are building Go based software which is used by thousands of customers. We want to share our experience on how we build reliable application and infrastructure architecture which allows us extending and dynamically patching our binary distribution on per customer basis. This talk also covers plugin build pipeline which can be shared with customers, and allow them extending the application by themselves.

**Comment by gonzaloserrano** [comment]
Thank you. Is Thursday the 31th a good date for your presentation?

**Comment by smoya** [comment]
This talk is scheduled for Jan 31, 2019. cc @buger
