### ISSUE TITLE
Talk - YAITSAHSUG - Yet Another Image Transformation Service At High Scale Using Golang

### ISSUE THREAD

**Issue by dcaba** [GolangBCN/talks#3]
- [x] I have read and agree the [Talk standards](https://github.com/GolangBCN/talks#talk-standards)

# YAITSAHSUG - Yet Another Image Transformation Service At High Scale Using Golang

"Given we've had the pleasure to build a global service in Schibsted to store and transform media contents for several marketplaces, we'd love to share some of the properties and tooling allowing us to maintain the service at scale, as well as continue developing it in a quite small team/squad with minimal ops overhead, connecting these properties also to some code snippets, implementation notes, thoughts and key learnings"

[Daniel Caballero](https://www.linkedin.com/in/danicaba/) is a Staff Devops/SRE/Systems/* Engineer at Schibsted, previously working for NTT and Oracle, who tries to having some fun with Golang, for instance, to create small services and tools like [tcpgoon](https://github.com/dachad/tcpgoon).

*Note: probably I will require some extra time... 45m + Q&As if possible, but I will share get the final figure and materials in the next days*

**Comment by smoya** [comment]
Thanks for your submitting. 45m + Q&As is ok 👍
