### ISSUE TITLE
Talk - Go gRPC Service from Dev to Production

### ISSUE THREAD

**Issue by myles-mcdonnell** [GolangBCN/talks#6]
* type: standard 
* level: medium to advanced
* language: english 
* twitter: @mylesmcdonnell
* email (optional): myles.mcdonnell@arche-digital.com
* linkedIn: https://www.linkedin.com/in/mylesmcdonnell/

- [x ] I have read and agree the [Talk standards](https://github.com/GolangBCN/talks#talk-standards)

# Go gRPC Service from Dev to Production

This talk is a whistle stop tour with live demo of a pipeline that goes from the creation of a new Go gRPC service, through development, testing and deployment onto a K8s cluster via helm and ConcourseCI.

Error handling, log aggregation, correlation IDs and many other topics and concerns that are vital to the operation of micro-services at scale are discussed and demonstrated.

If you would like to contact me to discuss please do so on Linkedin: https://www.linkedin.com/in/mylesmcdonnell/

**Comment by gonzaloserrano** [comment]
Hi @myles-mcdonnell, would you be available to make the talk in this month meetup? It will probably be in a couple of weeks.

**Comment by smoya** [comment]
This talk is going to be presented at November's Meetup.

Thanks @myles-mcdonnell !
