### ISSUE TITLE
Talk - Summoning the Go memory manager

### ISSUE THREAD

**Issue by mariomac** [GolangBCN/talks#7]
* type: standard
* level: medium
* language: english
* twitter: [@MaciasUPC](https://twitter.com/MaciasUPC)

- [X] I have read and agree the [Talk standards](https://github.com/GolangBCN/talks#talk-standards)

# Summoning the Go memory manager

"Passing pointers is faster than moving structs", they told us in CS grades. This assumption persisted in our mind and we never questioned that Go is neither C nor C++. Go manages the memory for us, but that doesn't mean that we can forget about memory management.
Knowing basic rules of Go memory allocation and management will allow us writing faster programs, thanks to faster memory allocations and less Garbage Collection.

**Comment by smoya** [comment]
This talk is going to be presented at November's Meetup. 

Thanks @mariomac !

**Comment by smoya** [comment]
This talk is scheduled for Jan 31, 2019. cc @mariomac
